using System.Collections;
using System.Collections.Generic;
using UnityEngine;


/* BY: ALIN
this script has a function called GenerateMessage which returns one [1] string containing a thing that
our chat would be saying at this point in time, based on some numbers corresponding to what the player
is doing right now.

ideally GenerateMessage should be called at different speeds, faster for when the monster is around
and much slower when nothing is happening

*/
public class ChatGeneration : MonoBehaviour
{
    [Tooltip("this is the chance that a regular message will be generated by GenerateMessage()")]
    public float RegularChance = 0.5f;
    [Tooltip("this is the chance that a scared/excited message will be generated by GenerateMessage()")]
    public float MonsterChance = 0.25f;
    [Tooltip("this is the chance that a monster request will be generated by GenerateMessage()")]
    public float RequestChance = 0.25f;
    [Tooltip("this is the monster GameObject whose EXACT NAME IN UNITY will be requested")]
    public GameObject MonsterObject;
    List<string> RegularChat = new List<string>
    {
        "This guy sucks",
        "hi is this the cooking stream",
        "can u do something cool",
        "hi",
        "can u wipe the camera lens",
        "how does it smell there",
        "ASYLUM",
        "kappa",
        "ill donate 50 ectoplasm if you scream at the top of your lungs rn",
        "I hope you're doing okay in there!!!!"
    };

    string GenerateMessage()
    {
        string message = null;

        message = RegularChat[UnityEngine.Random.Range(0,RegularChat.Count)];


        return message;
    }
}
